export const HERO_SLIDES = [
  {
    id: 1,
    image: '/images/hero-1.webp',
    title: 'راکت‌های حرفه‌ای تنیس',
    description: 'جدیدترین مدل‌های Wilson و Babolat با تخفیف ویژه',
  },
  {
    id: 2,
    image: '/images/hero-2.webp',
    title: 'کالکشن پدل 2024',
    description: 'بهترین راکت‌های پدل برای بازیکنان حرفه‌ای',
  },
  {
    id: 3,
    image: '/images/hero-3.webp',
    title: 'تجهیزات بدمینتون Yonex',
    description: 'راکت‌ها و توپ‌های استاندارد مسابقات جهانی',
  },
  {
    id: 4,
    image: '/images/hero-4.webp',
    title: 'محصولات اسکواش',
    description: 'راکت، کفش و اکسسوری با کیفیت برتر',
  },
];

export const BEST_SELLER_PRODUCTS = [
  {
    id: 1,
    name: 'راکت تنیس Wilson Pro Staff',
    price: 12500000,
    originalPrice: 15000000,
    discount: 17,
    image: '/images/product-1.webp',
    rating: 4.8,
    brand: 'Wilson',
    category: 'تنیس',
  },
  {
    id: 2,
    name: 'راکت بدمینتون Yonex Astrox',
    price: 8900000,
    originalPrice: 10500000,
    discount: 15,
    image: '/images/product-2.webp',
    rating: 4.9,
    brand: 'Yonex',
    category: 'بدمینتون',
  },
  {
    id: 3,
    name: 'راکت پدل Bullpadel Vertex',
    price: 14200000,
    originalPrice: null,
    discount: 0,
    image: '/images/product-3.webp',
    rating: 4.7,
    brand: 'Bullpadel',
    category: 'پدل',
  },
  {
    id: 4,
    name: 'کفش تنیس Nike Court Air Zoom',
    price: 6700000,
    originalPrice: 8000000,
    discount: 16,
    image: '/images/product-4.webp',
    rating: 4.6,
    brand: 'Nike',
    category: 'تنیس',
  },
  {
    id: 5,
    name: 'راکت اسکواش Dunlop Hyperfibre',
    price: 5400000,
    originalPrice: null,
    discount: 0,
    image: '/images/product-5.webp',
    rating: 4.5,
    brand: 'Dunlop',
    category: 'اسکواش',
  },
  {
    id: 6,
    name: 'توپ تنیس Wilson US Open',
    price: 890000,
    originalPrice: 1100000,
    discount: 19,
    image: '/images/product-6.webp',
    rating: 4.9,
    brand: 'Wilson',
    category: 'تنیس',
  },
  {
    id: 7,
    name: 'راکت پینگ‌پنگ Butterfly Timo Boll',
    price: 3200000,
    originalPrice: null,
    discount: 0,
    image: '/images/product-7.webp',
    rating: 4.8,
    brand: 'Butterfly',
    category: 'پینگ‌پنگ',
  },
  {
    id: 8,
    name: 'کوله پشتی تنیس Babolat Pure Drive',
    price: 4500000,
    originalPrice: 5200000,
    discount: 13,
    image: '/images/product-8.webp',
    rating: 4.7,
    brand: 'Babolat',
    category: 'تنیس',
  },
  {
    id: 9,
    name: 'راکت بدمینتون Victor Jetspeed',
    price: 7800000,
    originalPrice: null,
    discount: 0,
    image: '/images/product-2.webp',
    rating: 4.6,
    brand: 'Victor',
    category: 'بدمینتون',
  },
  {
    id: 10,
    name: 'چسب راکت تنیس Head Hydrosorb',
    price: 420000,
    originalPrice: 550000,
    discount: 24,
    image: '/images/product-1.webp',
    rating: 4.8,
    brand: 'Head',
    category: 'تنیس',
  },
];

export const AMAZING_OFFER_PRODUCTS = [
  {
    id: 11,
    name: 'راکت تنیس Head Graphene 360',
    price: 9800000,
    originalPrice: 14000000,
    discount: 30,
    image: '/images/product-3.webp',
    rating: 4.8,
    brand: 'Head',
    category: 'تنیس',
  },
  {
    id: 12,
    name: 'ست توپ بدمینتون Yonex',
    price: 1250000,
    originalPrice: 1800000,
    discount: 31,
    image: '/images/product-4.webp',
    rating: 4.7,
    brand: 'Yonex',
    category: 'بدمینتون',
  },
  {
    id: 13,
    name: 'راکت پدل Head Delta Pro',
    price: 11900000,
    originalPrice: 17500000,
    discount: 32,
    image: '/images/product-5.webp',
    rating: 4.9,
    brand: 'Head',
    category: 'پدل',
  },
  {
    id: 14,
    name: 'کفش اسکواش Dunlop Ultimate',
    price: 4200000,
    originalPrice: 6500000,
    discount: 35,
    image: '/images/product-6.webp',
    rating: 4.6,
    brand: 'Dunlop',
    category: 'اسکواش',
  },
  {
    id: 15,
    name: 'میز پینگ‌پنگ Stiga Premium',
    price: 18500000,
    originalPrice: 25000000,
    discount: 26,
    image: '/images/product-7.webp',
    rating: 4.8,
    brand: 'Stiga',
    category: 'پینگ‌پنگ',
  },
  {
    id: 16,
    name: 'راکت تنیس Babolat Pure Aero',
    price: 10200000,
    originalPrice: 15000000,
    discount: 32,
    image: '/images/product-8.webp',
    rating: 4.9,
    brand: 'Babolat',
    category: 'تنیس',
  },
  {
    id: 17,
    name: 'کیف بدمینتون Victor BR3602',
    price: 2800000,
    originalPrice: 4000000,
    discount: 30,
    image: '/images/product-8.webp',
    rating: 4.7,
    brand: 'Victor',
    category: 'بدمینتون',
  },
  {
    id: 18,
    name: 'عینک ورزشی Oakley Radar',
    price: 3500000,
    originalPrice: 5500000,
    discount: 36,
    image: '/images/product-8.webp',
    rating: 4.8,
    brand: 'Oakley',
    category: 'اکسسوری',
  },
  {
    id: 19,
    name: 'مچ‌بند تنیس Nike Dri-Fit',
    price: 580000,
    originalPrice: 850000,
    discount: 32,
    image: '/images/product-5.webp',
    rating: 4.5,
    brand: 'Nike',
    category: 'اکسسوری',
  },
  {
    id: 20,
    name: 'راکت اسکواش Tecnifibre Carboflex',
    price: 6200000,
    originalPrice: 9000000,
    discount: 31,
    image: '/images/product-6.webp',
    rating: 4.8,
    brand: 'Tecnifibre',
    category: 'اسکواش',
  },
];

export const ARTICLES = [
  {
    id: 1,
    title: 'راهنمای انتخاب راکت تنیس مناسب',
    image: '/images/article-1.webp',
    slug: 'tennis-racket-guide',
    excerpt: 'نکات کلیدی برای انتخاب راکت تنیس متناسب با سطح بازی شما',
  },
  {
    id: 2,
    title: 'تکنیک‌های پیشرفته بدمینتون',
    image: '/images/article-2.webp',
    slug: 'badminton-techniques',
    excerpt: 'آموزش حرفه‌ای ضربات اسمش و دراپ در بدمینتون',
  },
  {
    id: 3,
    title: 'تفاوت پدل و تنیس',
    image: '/images/article-3.webp',
    slug: 'padel-vs-tennis',
    excerpt: 'مقایسه کامل دو ورزش پدل و تنیس از نظر قوانین و تجهیزات',
  },
  {
    id: 4,
    title: 'بهترین برندهای راکت اسکواش',
    image: '/images/article-4.webp',
    slug: 'squash-brands',
    excerpt: 'معرفی برترین سازندگان راکت‌های اسکواش در جهان',
  },
  {
    id: 5,
    title: 'آموزش پینگ‌پنگ برای مبتدیان',
    image: '/images/article-5.webp',
    slug: 'pingpong-beginners',
    excerpt: 'راهنمای گام به گام شروع بازی پینگ‌پنگ',
  },
  {
    id: 6,
    title: 'نگهداری راکت‌های ورزشی',
    image: '/images/article-6.webp',
    slug: 'racket-maintenance',
    excerpt: 'چگونه از راکت خود مراقبت کنیم تا عمر بیشتری داشته باشد',
  },
];

export const BRAND_LOGOS = [
  'Wilson',
  'Babolat',
  'Head',
  'Yonex',
  'Dunlop',
  'Tecnifibre',
  'Bullpadel',
  'Victor',
  'Li-Ning',
  'Butterfly',
  'Stiga',
  'Prince',
  'Nike',
  'Adidas',
  'Asics',
];
