import connectToDB from "base/configs/db";
import Sport from "base/models/Sport";
import {registerSlug} from "base/actions/registerSlug";

export async function POST(req) {
  try {
    await connectToDB();

    const { name, description, icon } = await req.json();

    // validate
    if (!name || name.trim() === "") {
      return Response.json(
        { error: "Name is required" },
        { status: 400 }
      );
    }

    // duplicate check (name)
    const exists = await Sport.findOne({ name: name.trim() });
    if (exists) {
      return Response.json(
        { error: "Sport already exists" },
        { status: 409 }
      );
    }

    // create sport (slug auto-generated by model)
    const created = await Sport.create({
      name: name.trim(),
      description: description || "",
      icon: icon || "",
    });

    // register slug in SlugRegistry
    await registerSlug({
      slug: created.slug,
      type: "sport",
      model: "Sport",
      refId: created._id,
      filterField: "sport",
      filterValue: created._id,
      label: created.name,
      parentSlug: null,
    });

    return Response.json(
      {
        message: "Sport created successfully",
        sport: created,
      },
      { status: 201 }
    );
  } catch (err) {
    return Response.json(
      { error: err.message },
      { status: 500 }
    );
  }
}
